name: All My Latest posts workflow
on:
  schedule:
    # Runs every hour
    - cron: '1  * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://techknowspace.wordpress.com/author/abhiramreddy31/feed/,https://iq.opengenus.org/author/abhiram/rss/,https://medium.com/feed/@abhiram.reddy,https://matrixread.com/author/abhiramreddy31/feed/"
          max_post_count: 100  
