name: All My Latest posts workflow
on:
  schedule:
    # Runs every hour
    - cron: '* * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://iq.opengenus.org/author/abhiram/rss/,https://matrixread.com/author/abhi/feed/"
          max_post_count: 10
